version: 0.2
phases:
  build:
    commands:

      # Fetch only secretstring
      # - secretstring=$(aws secretsmanager get-secret-value --secret-id ssh --query SecretString --output json)
      - aws secretsmanager get-secret-value --secret-id ssh_ok --query SecretString --output text > ssh.txt
      # Extract the value directly if SecretString is a JSON object
      # - echo $secretstring | jq -r '. | fromjson | .ssh_name' > ssh.txt
      
      - cat ssh.txt
      - chmod 600 ssh.txt
      - ls -l ssh.txt

      
      - echo "Fetching IP address from Secret Manager"
      - export INSTANCE_IP=$(aws secretsmanager get-secret-value --secret-id ip --query SecretString --output text | jq -r .ip)
      - echo $INSTANCE_IP

      - echo "Connecting to EC2 instance and running script"
      - ssh -i ssh.txt ubuntu@$INSTANCE_IP "bash /home/ubuntu/script.sh"


