version: 0.2
phases:
  build:
    commands:

      # Fetch only secretstring
      - secretstring=$(aws secretsmanager get-secret-value --secret-id ssh --query SecretString --output json)
      
      # Extract the value directly if SecretString is a JSON object
      - echo $secretstring | jq -r '. | fromjson | .ssh_name' > ssh.txt
      
      # # Print the secret value
      
      # - cat ssh.txt
      # Extract content between "-----BEGIN RSA PRIVATE KEY-----" and "-----END RSA PRIVATE KEY-----" and format as JSON
      - PRIVATE_KEY_JSON=$(sed -n '/-----BEGIN RSA PRIVATE KEY-----/{:a;N;/-----END RSA PRIVATE KEY-----/!ba;s/\n/\\n/g;p}' ssh.txt | jq -Rs .)

      # Save the JSON-formatted content to a file
      - echo $PRIVATE_KEY_JSON > private_key.txt

      # - chmod 600 ssh.txt

      
      # - echo "Fetching IP address from Secret Manager"
      # - INSTANCE_IP=$(aws secretsmanager get-secret-value --secret-id ip --query SecretString --output text | jq -r .ip)
      # - echo $INSTANCE_IP

      # - echo "Connecting to EC2 instance and running script"
      # - ssh -i ssh.txt ubuntu@"$INSTANCE_IP" "bash /home/ubuntu/script.sh"

