version: 0.2

phases:
  build:
    commands:
      - echo "Fetching SSH key from Secret Manager"
      - aws secretsmanager get-secret-value --secret-id ssh --query SecretString --output text > ssh.txt
      - echo  ssh.txt
      - cat ssh.txt
      # - chmod 600 file.pem
      # - ls -l file.pem

      # - echo "Fetching IP address from Secret Manager"
      # - INSTANCE_IP=$(aws secretsmanager get-secret-value --secret-id ip --query SecretString --output text | jq -r .ip)
      # - echo $INSTANCE_IP

      # - echo "Connecting to EC2 instance and running script"
      # - ssh -i file.pem -o StrictHostKeyChecking=no ubuntu@$INSTANCE_IP "bash /home/ubuntu/script.sh"

# post_build:
#   commands:
#     - echo "Build completed on $(date)"
