version: 0.2
phases:
  build:
    commands:

      # Fetch only secretstring
      - secretstring=$(aws secretsmanager get-secret-value --secret-id ssh --query SecretString --output json)
      
      # Extract the value directly if SecretString is a JSON object
      - echo $secretstring | jq -r '. | fromjson | .ssh_name' > ssh.text
      
      # Print the secret value
      
      - echo $ssh_name
      - chmod 600 ssh.text

      
      - echo "Fetching IP address from Secret Manager"
      - INSTANCE_IP=$(aws secretsmanager get-secret-value --secret-id ip --query SecretString --output text | jq -r .ip)
      - echo $INSTANCE_IP

      - echo "Connecting to EC2 instance and running script"
      - ssh -i ssh.text ubuntu@$INSTANCE_IP "bash /home/ubuntu/script.sh"

